export const PRICES = [
  {
    id: 'starter',
    name: 'Starter Pack',
    price: 20,
    credits: 4,
    perSong: 5,
    description: 'Perfect for trying it out',
    stripePriceId: process.env.STRIPE_PRICE_ID_STARTER,
  },
  {
    id: 'pro',
    name: 'Pro Pack',
    price: 80,
    credits: 20,
    perSong: 4,
    description: 'Save 20%',
    popular: true,
    stripePriceId: process.env.STRIPE_PRICE_ID_PRO,
  },
  {
    id: 'team',
    name: 'Corporate Pack',
    price: 175,
    credits: 50,
    perSong: 3.5,
    description: 'Save 30%',
    stripePriceId: process.env.STRIPE_PRICE_ID_TEAM,
  },
]
