import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Plus, Music, Download } from 'lucide-react'
import { Badge } from '@/components/ui/badge'

export default async function SongsPage() {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  // Fetch user's teams to get team IDs
  const { data: teamMembers } = await supabase
    .from('team_members')
    .select('team_id')
    .eq('user_id', user.id)

  const teamIds = teamMembers?.map((tm: any) => tm.team_id) || []

  let songs: any[] = []

  if (teamIds.length > 0) {
    const { data } = await supabase
      .from('songs')
      .select('*, teams(name)')
      .in('team_id', teamIds)
      .order('created_at', { ascending: false })
    
    songs = data || []
  }

  return (
    <div className="flex-1 space-y-8 p-8 pt-6">
      <div className="flex items-center justify-between space-y-2">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Songs</h2>
          <p className="text-muted-foreground">
            All songs generated by your teams.
          </p>
        </div>
        <div className="flex items-center space-x-2">
          <Link href="/songs/new">
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Generate Song
            </Button>
          </Link>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {songs.length === 0 ? (
           <div className="col-span-full text-center py-12 border rounded-lg border-dashed">
             <Music className="h-10 w-10 text-muted-foreground mx-auto mb-4" />
             <h3 className="text-lg font-medium">No songs yet</h3>
             <p className="text-muted-foreground mb-4">Start by generating your first team song.</p>
             <Link href="/songs/new">
               <Button>Create Song</Button>
             </Link>
           </div>
        ) : (
          songs.map((song) => (
            <Card key={song.id} className="flex flex-col">
              <CardHeader>
                <div className="flex justify-between items-start">
                    <div className="space-y-1">
                        <CardTitle className="line-clamp-1 text-lg">{song.title}</CardTitle>
                        <CardDescription>{song.teams?.name}</CardDescription>
                    </div>
                    <Badge variant={song.status === 'complete' ? 'default' : 'secondary'}>
                        {song.status}
                    </Badge>
                </div>
              </CardHeader>
              <CardContent className="flex-1 flex flex-col gap-4">
                <div className="flex-1 space-y-2">
                    <div className="text-sm">
                        <span className="font-medium">Genre:</span> <span className="capitalize">{song.genre}</span>
                    </div>
                    <div className="text-sm text-muted-foreground line-clamp-3 italic">
                        {song.lyrics ? `"${song.lyrics.slice(0, 100)}..."` : "Lyrics generating..."}
                    </div>
                </div>
                <div className="flex items-center gap-2 mt-auto pt-2">
                    <Link href={`/songs/${song.id}`} className="flex-1">
                        <Button variant="outline" className="w-full">
                            View Details
                        </Button>
                    </Link>
                    {song.audio_url && (
                        <a href={song.audio_url} download target="_blank" rel="noopener noreferrer">
                            <Button variant="ghost" size="icon" title="Download">
                                <Download className="h-4 w-4" />
                            </Button>
                        </a>
                    )}
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  )
}